### ISSUE TITLE
There are no issues.

### ISSUE THREAD

**Issue by cbfx** [rackerlabs/zoolander#270]
howdy! sorry to barge in here but i have notifications popping up for this repo and figured this is a good time and place to chime in. i noticed y'all don't have any issues posted. if there were issues, i'd enjoy being able to contribute somehow.

anyone got anything i can do to help?

**Comment by amberRrucker** [comment]
Oh man @cbfx do we have issues. 
We can talk about issues and a more truely open repo with the team down here in ecomm and get posting if you don't mind a smidge of a wait on those issues.

**Comment by cbfx** [comment]
not a problem. i'll be lurking until then.

:poof:

**Comment by amberRrucker** [comment]
@SyntaxStacks @bighappyface @ejchiefs - this warrants some wheaties time probably. Thursday?

**Comment by SyntaxStacks** [comment]
I've invited @cbfx to the slack channel and I agree that posting issues here for contribution isn't a bad idea.

**Comment by brady-vitrano** [comment]
+1 on the issues 😛
