### ISSUE TITLE
EJ can't bag groceries

### ISSUE THREAD

**Issue by runrog** [rackerlabs/zoolander#596]
I went to HEB yesterday and this dude named @ejchiefs bagged my stuff and all of it tore apart. yes you suck

**Comment by brantdarilek** [comment]
![giphy](https://user-images.githubusercontent.com/799053/49110969-7c37b380-f254-11e8-8718-e70410dbea49.gif)

**Comment by WidgetsBurritos** [comment]
Closing per @mikerastiello's refusal.

**Comment by mikerastiello** [comment]
![ej-heb](https://user-images.githubusercontent.com/3303014/49251669-91911700-f3e7-11e8-8440-8b928efc6cac.png)
